name = "mist_server"
version = "1.0.0"
target = "erlang"

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_http = ">= 4.1.1 and < 5.0.0"
mist = ">= 5.0.0 and < 6.0.0"
hinoto = { path = "../.." }

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
